version: '3.1'

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: documentDB
      MYSQL_USER: KBB-dev
      MYSQL_PASSWORD: documentDB-pw
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  document-management-service:
    build:
      context: ./documentManagementService
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/documentDB
      SPRING_DATASOURCE_USERNAME: KBB-dev
      SPRING_DATASOURCE_PASSWORD: documentDB-pw
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - 8080:8080