# Docker Compose file for setting up a MariaDB service.
version: '3.1'

services:

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: documentDB
      MYSQL_USER: KBB-dev
      MYSQL_PASSWORD: documentDB-pw
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  mariadb_authentication:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: authenticationDB
      MYSQL_USER: auth-dev
      MYSQL_PASSWORD: authDB-pw
    volumes:
      - ./data_authentication:/var/lib/mysql
    ports:
      - "3307:3306"