spring:
  application:
    name: DocumentManagementService
    file-directory: "C:\\Users\\Hasnat\\Downloads\\KBB-test\\"
  datasource:
    url: jdbc:mariadb://localhost:3306/documentDB
    username: KBB-dev
    password: documentDB-pw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
  devtools:
    restart:
      enabled: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs
  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false

logging:
  level:
    org.springframework.data.rest: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    # org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
