spring:
  application:
    name: DocumentManagementService  # Name of the Spring application
    file-directory: "C:\\Users\\Hasnat\\Downloads\\KBB-test\\"
  datasource:
    url: jdbc:mariadb://localhost:3306/documentDB  # URL for the MariaDB datasource
    username: KBB-dev  # Username for database connection
    password: documentDB-pw  # Password for database connection
    driver-class-name: org.mariadb.jdbc.Driver  # JDBC driver class name
  jpa:
    show-sql: true  # Show SQL statements in console
    hibernate:
      ddl-auto: update  # Hibernate auto DDL update
    properties:
      hibernate:
        format_sql: true  # Format SQL for better readability
        use_sql_comments: true  # Include comments in generated SQL
        dialect: org.hibernate.dialect.MariaDBDialect  # Database dialect
  devtools: # Tool for Hot-Reloading
    restart:
      enabled: true
  springdoc:
    swagger-ui:
      path: /swagger-ui.html  # Path for Swagger UI
    api-docs:
      path: /api-docs  # Path for API documentation
  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  profiles:
    active: prod  # Active Spring profile
  ldap:
    embedded:
      port: 8389  # Port for embedded LDAP server
      base-dn: dc=springframework,dc=org  # Base DN for LDAP
      ldif: classpath:test-server.ldif  # LDIF file for LDAP initialization

server:
  port: 8080  # Port on which the server runs

user:
  control:
    url: http://localhost:8080/usercontrol  # URL for user control functionality

# variables
active:
  directory:
    url: ldap://localhost:10389  # URL for active directory
    domain: example.com  # Domain for active directory
    search:
      base: ou=people,dc=springframework,dc=org  # Base search path in active directory
      filter: (objectClass=person)  # Filter for searching in active directory
    binding:
      user: uid=admin,ou=system  # Binding user for active directory

path:
  to:
    active-directory-binding-pwd: documentManagementService/src/main/resources/active-directory-binding-pwd.csv  # Path to the active directory binding password CSV file


logging:
  level:
    root: DEBUG  # Root logging level
    org.springframework: DEBUG  # Logging level for Spring framework
    org.springframework.data.rest: DEBUG  # Logging level for Spring Data REST
    # org.springframework.web.servlet.mvc.method.annotation: DEBUG
